<?php

/**
 * BaseChannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $subtitle
 * @property string $author
 * @property string $summary
 * @property string $description
 * @property string $category
 * @property string $image
 * @property string $link
 * @property string $language
 * @property string $copyright
 * @property boolean $explicit
 * @property Doctrine_Collection $Items
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getSubtitle()    Returns the current record's "subtitle" value
 * @method string              getAuthor()      Returns the current record's "author" value
 * @method string              getSummary()     Returns the current record's "summary" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getCategory()    Returns the current record's "category" value
 * @method string              getImage()       Returns the current record's "image" value
 * @method string              getLink()        Returns the current record's "link" value
 * @method string              getLanguage()    Returns the current record's "language" value
 * @method string              getCopyright()   Returns the current record's "copyright" value
 * @method boolean             getExplicit()    Returns the current record's "explicit" value
 * @method Doctrine_Collection getItems()       Returns the current record's "Items" collection
 * @method Channel             setTitle()       Sets the current record's "title" value
 * @method Channel             setSubtitle()    Sets the current record's "subtitle" value
 * @method Channel             setAuthor()      Sets the current record's "author" value
 * @method Channel             setSummary()     Sets the current record's "summary" value
 * @method Channel             setDescription() Sets the current record's "description" value
 * @method Channel             setCategory()    Sets the current record's "category" value
 * @method Channel             setImage()       Sets the current record's "image" value
 * @method Channel             setLink()        Sets the current record's "link" value
 * @method Channel             setLanguage()    Sets the current record's "language" value
 * @method Channel             setCopyright()   Sets the current record's "copyright" value
 * @method Channel             setExplicit()    Sets the current record's "explicit" value
 * @method Channel             setItems()       Sets the current record's "Items" collection
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChannel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('channel');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('summary', 'string', 600, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 600,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('category', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('language', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('copyright', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('explicit', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item as Items', array(
             'local' => 'id',
             'foreign' => 'channel_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}