<?php

/**
 * BaseItemFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $item_id
 * @property string $filename
 * @property string $caption
 * @property Item $Item
 * 
 * @method integer  getItemId()   Returns the current record's "item_id" value
 * @method string   getFilename() Returns the current record's "filename" value
 * @method string   getCaption()  Returns the current record's "caption" value
 * @method Item     getItem()     Returns the current record's "Item" value
 * @method ItemFile setItemId()   Sets the current record's "item_id" value
 * @method ItemFile setFilename() Sets the current record's "filename" value
 * @method ItemFile setCaption()  Sets the current record's "caption" value
 * @method ItemFile setItem()     Sets the current record's "Item" value
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_file');
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('caption', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}