<?php

/**
 * BaseToken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mixtape_id
 * @property integer $subscriber_id
 * @property bool $is_valid
 * @property Mixtape $Mixtape
 * @property Subscriber $Subscriber
 * 
 * @method integer    getMixtapeId()     Returns the current record's "mixtape_id" value
 * @method integer    getSubscriberId()  Returns the current record's "subscriber_id" value
 * @method bool       getIsValid()       Returns the current record's "is_valid" value
 * @method Mixtape    getMixtape()       Returns the current record's "Mixtape" value
 * @method Subscriber getSubscriber()    Returns the current record's "Subscriber" value
 * @method Token      setMixtapeId()     Sets the current record's "mixtape_id" value
 * @method Token      setSubscriberId()  Sets the current record's "subscriber_id" value
 * @method Token      setIsValid()       Sets the current record's "is_valid" value
 * @method Token      setMixtape()       Sets the current record's "Mixtape" value
 * @method Token      setSubscriber()    Sets the current record's "Subscriber" value
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseToken extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('token');
        $this->hasColumn('mixtape_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('subscriber_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_valid', 'bool', null, array(
             'type' => 'bool',
             'notnull' => false,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mixtape', array(
             'local' => 'mixtape_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Subscriber', array(
             'local' => 'subscriber_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}