<?php

/**
 * BaseSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property Doctrine_Collection $Token
 * 
 * @method string              getEmail() Returns the current record's "email" value
 * @method Doctrine_Collection getToken() Returns the current record's "Token" collection
 * @method Subscriber          setEmail() Sets the current record's "email" value
 * @method Subscriber          setToken() Sets the current record's "Token" collection
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubscriber extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscriber');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Token', array(
             'local' => 'id',
             'foreign' => 'subscriber_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}