<?php

/**
 * Basechannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $subtitle
 * @property string $author
 * @property string $summary
 * @property string $description
 * @property string $category
 * @property string $image
 * @property string $link
 * @property string $language
 * @property string $copyright
 * @property boolean $explicit
 * 
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getSubtitle()    Returns the current record's "subtitle" value
 * @method string  getAuthor()      Returns the current record's "author" value
 * @method string  getSummary()     Returns the current record's "summary" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getCategory()    Returns the current record's "category" value
 * @method string  getImage()       Returns the current record's "image" value
 * @method string  getLink()        Returns the current record's "link" value
 * @method string  getLanguage()    Returns the current record's "language" value
 * @method string  getCopyright()   Returns the current record's "copyright" value
 * @method boolean getExplicit()    Returns the current record's "explicit" value
 * @method channel setTitle()       Sets the current record's "title" value
 * @method channel setSubtitle()    Sets the current record's "subtitle" value
 * @method channel setAuthor()      Sets the current record's "author" value
 * @method channel setSummary()     Sets the current record's "summary" value
 * @method channel setDescription() Sets the current record's "description" value
 * @method channel setCategory()    Sets the current record's "category" value
 * @method channel setImage()       Sets the current record's "image" value
 * @method channel setLink()        Sets the current record's "link" value
 * @method channel setLanguage()    Sets the current record's "language" value
 * @method channel setCopyright()   Sets the current record's "copyright" value
 * @method channel setExplicit()    Sets the current record's "explicit" value
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basechannel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('channel');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('summary', 'string', 600, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 600,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('category', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('language', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('copyright', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('explicit', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}