<?php

/**
 * BaseAdvertisement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $banner
 * @property string $content
 * @property timestamp $is_published
 * 
 * @method string        getTitle()        Returns the current record's "title" value
 * @method string        getBanner()       Returns the current record's "banner" value
 * @method string        getContent()      Returns the current record's "content" value
 * @method timestamp     getIsPublished()  Returns the current record's "is_published" value
 * @method Advertisement setTitle()        Sets the current record's "title" value
 * @method Advertisement setBanner()       Sets the current record's "banner" value
 * @method Advertisement setContent()      Sets the current record's "content" value
 * @method Advertisement setIsPublished()  Sets the current record's "is_published" value
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertisement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advertisement');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('banner', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('is_published', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}