<?php

/**
 * Baseitem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $subtitle
 * @property string $author
 * @property string $summary
 * @property string $image
 * @property string $url
 * @property integer $lenght
 * @property enum $type
 * @property timestamp $pub_date
 * @property string $duration
 * @property string $keywords
 * @property channel $Channel
 * 
 * @method string    getTitle()    Returns the current record's "title" value
 * @method string    getSubtitle() Returns the current record's "subtitle" value
 * @method string    getAuthor()   Returns the current record's "author" value
 * @method string    getSummary()  Returns the current record's "summary" value
 * @method string    getImage()    Returns the current record's "image" value
 * @method string    getUrl()      Returns the current record's "url" value
 * @method integer   getLenght()   Returns the current record's "lenght" value
 * @method enum      getType()     Returns the current record's "type" value
 * @method timestamp getPubDate()  Returns the current record's "pub_date" value
 * @method string    getDuration() Returns the current record's "duration" value
 * @method string    getKeywords() Returns the current record's "keywords" value
 * @method channel   getChannel()  Returns the current record's "Channel" value
 * @method item      setTitle()    Sets the current record's "title" value
 * @method item      setSubtitle() Sets the current record's "subtitle" value
 * @method item      setAuthor()   Sets the current record's "author" value
 * @method item      setSummary()  Sets the current record's "summary" value
 * @method item      setImage()    Sets the current record's "image" value
 * @method item      setUrl()      Sets the current record's "url" value
 * @method item      setLenght()   Sets the current record's "lenght" value
 * @method item      setType()     Sets the current record's "type" value
 * @method item      setPubDate()  Sets the current record's "pub_date" value
 * @method item      setDuration() Sets the current record's "duration" value
 * @method item      setKeywords() Sets the current record's "keywords" value
 * @method item      setChannel()  Sets the current record's "Channel" value
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('summary', 'string', 600, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 600,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lenght', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'audio/mpeg',
              1 => 'video/mp4',
             ),
             'default' => 'audio/mpeg',
             ));
        $this->hasColumn('pub_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('duration', 'string', 16, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 16,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'muchobeat, mucho beat, music',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('channel as Channel', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}