<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $channel_id
 * @property string $title
 * @property string $subtitle
 * @property string $author
 * @property string $summary
 * @property string $image
 * @property string $url
 * @property integer $lenght
 * @property enum $type
 * @property timestamp $pub_date
 * @property string $duration
 * @property string $keywords
 * @property Channel $Channel
 * @property ItemFile $ItemFile
 * 
 * @method integer   getChannelId()  Returns the current record's "channel_id" value
 * @method string    getTitle()      Returns the current record's "title" value
 * @method string    getSubtitle()   Returns the current record's "subtitle" value
 * @method string    getAuthor()     Returns the current record's "author" value
 * @method string    getSummary()    Returns the current record's "summary" value
 * @method string    getImage()      Returns the current record's "image" value
 * @method string    getUrl()        Returns the current record's "url" value
 * @method integer   getLenght()     Returns the current record's "lenght" value
 * @method enum      getType()       Returns the current record's "type" value
 * @method timestamp getPubDate()    Returns the current record's "pub_date" value
 * @method string    getDuration()   Returns the current record's "duration" value
 * @method string    getKeywords()   Returns the current record's "keywords" value
 * @method Channel   getChannel()    Returns the current record's "Channel" value
 * @method ItemFile  getItemFile()   Returns the current record's "ItemFile" value
 * @method Item      setChannelId()  Sets the current record's "channel_id" value
 * @method Item      setTitle()      Sets the current record's "title" value
 * @method Item      setSubtitle()   Sets the current record's "subtitle" value
 * @method Item      setAuthor()     Sets the current record's "author" value
 * @method Item      setSummary()    Sets the current record's "summary" value
 * @method Item      setImage()      Sets the current record's "image" value
 * @method Item      setUrl()        Sets the current record's "url" value
 * @method Item      setLenght()     Sets the current record's "lenght" value
 * @method Item      setType()       Sets the current record's "type" value
 * @method Item      setPubDate()    Sets the current record's "pub_date" value
 * @method Item      setDuration()   Sets the current record's "duration" value
 * @method Item      setKeywords()   Sets the current record's "keywords" value
 * @method Item      setChannel()    Sets the current record's "Channel" value
 * @method Item      setItemFile()   Sets the current record's "ItemFile" value
 * 
 * @package    podcastadmin
 * @subpackage model
 * @author     Enrique Garcia <enrique@inodata.com.mx>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('channel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('summary', 'string', 600, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 600,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lenght', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'audio/mpeg',
              1 => 'video/mp4',
             ),
             'default' => 'audio/mpeg',
             ));
        $this->hasColumn('pub_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('duration', 'string', 16, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 16,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'muchobeat, mucho beat, music',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Channel', array(
             'local' => 'channel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ItemFile', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}