<?php

/**
 * ItemFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemFile');
    }
}