<?php

/**
 * itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('item');
    }
}