<?php

/**
 * MixtapeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MixtapeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MixtapeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mixtape');
    }
}