generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Item
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        pub_date: { label: "Released", date_format: "d/M/y" }
      list:
        display:  [ =title, subtitle, pub_date ]
      filter:
        display:  [ channel_id, title, author, pub_date, keywords ]
      form:
#        display:  [ channel_id, title, author, subtitle, summary, pub_date, keywords, attachment ]
      edit:    ~
      new:     ~
